---
- name: Install dependencies
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - git
    - curl
    - build-essential
    - libssl-dev
  tags: nvm

- name: Install nvm
  git: repo=https://github.com/creationix/nvm.git dest=~/.nvm version={{ nvm_version }}
  tags: nvm

- name: Source nvm in ~/.profile
  lineinfile: >
    dest=~/.profile
    line="source ~/.nvm/nvm.sh"
  tags: nvm

- name: Install {{ node_version }}
  shell: . ~/.nvm/nvm.sh && nvm install {{ node_version }}
  args:
    executable: /bin/bash
  register: nvm_install_result
  changed_when: "'is already installed.' not in nvm_install_result.stderr"
  tags: nvm

- name: Check if {{ node_version }} is the default node version
  shell: echo $NVM_NO_COLORS && . ~/.nvm/nvm.sh && nvm ls --no-colors | grep -e 'default -> {{ node_version }}'
  args:
    executable: /bin/bash
  register: nvm_check_default
  changed_when: False
  ignore_errors: True
  tags: nvm

- name: Set default node version to {{ node_version }}
  shell: . ~/.nvm/nvm.sh && nvm alias --no-colors default {{ node_version }}
  args:
    executable: /bin/bash
  when: nvm_check_default|failed
  tags: nvm
