---
- name: check ansible version
  assert:
    that: ansible_version.major > 2 or (ansible_version.major == 2 and ansible_version.minor >= 2 )

- name: Update all packages (aptitude safe-upgrade)
  become: true
  apt: upgrade=safe update_cache=yes

- name: Set password for pi user
  become: true
  user: name=pi password="{{password}}" generate_ssh_key=yes

- name: Set hostname
  become: true
  hostname: name="{{inventory_hostname}}"

- name: Set hostname (/etc/hosts)
  become: true
  lineinfile:
    dest: /etc/hosts
    regexp: "^127.0.0.1"
    line: "127.0.0.1 {{inventory_hostname}}{% if inventory_hostname != inventory_hostname_short %} {{inventory_hostname_short}}{% endif %} localhost"

- name: Generate locale {{locale}}
  become: true
  locale_gen: name={{locale}} state=present

- name: Set locale LANG={{locale}}
  become: true
  command: update-locale LANG={{locale}}
  changed_when: false

- name: "Set timezone to {{timezone}}"
  become: true
  timezone: "name={{timezone}}"
  changed_when: false

- name: Install vim
  become: true
  apt: name=vim

- name: Use vim as default
  become: true
  alternatives: name=editor path=/usr/bin/vim.basic

- name: Additional aliases
  lineinfile:
    dest: ~/.bash_aliases
    regexp: "^alias l="
    line: "alias l='ls -lA'"
    create: yes
    mode: 0644

- name: Set SSH-Key for pi user
  become: true
  authorized_key: user=pi key="{{ lookup('file', sshKey) }}"
