- name: git repo
  git: repo=https://github.com/not-implemented/raspicam-timelapse.git dest="{{repo_path}}"

- name: npm install
  npm: path={{repo_path}}

- name: create capture directory
  file: path="{{ capture_path }}" state=directory

- name: install systemd service
  become: true
  template:
    src: raspicam-timelapse.service
    dest: /etc/systemd/system/raspicam-timelapse.service
    owner: pi
    group: pi
    mode: 0644

- name: read timelapse.json config
  slurp:
    src: "{{ repo_path + '/config/timelapse.json' }}"
  register: timelapse_json_raw
  ignore_errors: true

- name: set timelapse.json config fact
  set_fact: timelapse_json="{{ timelapse_json_raw['content'] | b64decode | from_json }}"
  when: timelapse_json_raw | succeeded

# TODO: don't change if it will be changed by ramdisk role later 
- name: write modified timelapse.json config
  copy: content="{{ timelapse_json | default({}) | combine({ 'capturePath':capture_path, 'username':webinterface_username, 'password':webinterface_password }) }}" dest="{{repo_path}}/config/timelapse.json"
  notify: 
  - restart raspicam-timelapse

- name: enable/start systemd service
  become: true
  systemd:
    name: raspicam-timelapse
    enabled: yes
    state: started
    daemon_reload: yes

- name: start capture cron entry
  cron:
      name: "start capture cron entry"
      minute: "{{start_capture_cron_minute}}"
      hour: "{{start_capture_cron_hour}}"
      month: "{{start_capture_cron_month}}"
      day: "{{start_capture_cron_day}}"
      weekday: "{{start_capture_cron_weekday}}"
      job: "curl -u {{webinterface_username}}:{{webinterface_password}} -k 'https://localhost:4443/api?action=startCapture'"
  when: setup_start_stop_capture_cron

- name: stop capture cron entry
  cron:
      name: "stop capture cron entry"
      minute: "{{stop_capture_cron_minute}}"
      hour: "{{stop_capture_cron_hour}}"
      month: "{{stop_capture_cron_month}}"
      day: "{{stop_capture_cron_day}}"
      weekday: "{{stop_capture_cron_weekday}}"
      job: "curl -u {{webinterface_username}}:{{webinterface_password}} -k 'https://localhost:4443/api?action=stopCapture'"
  when: setup_start_stop_capture_cron

- name: stop capture fs full cron entry
  cron:
      name: "stop capture fs full cron entry"
      minute: "*/15"
      hour: "*"
      month: "{{start_capture_cron_month}}"
      day: "{{start_capture_cron_day}}"
      weekday: "{{start_capture_cron_weekday}}"
      job: "df --output=pcent /home/pi/capture | tail -n 1 | grep -qE '^( 9[7-9]|100)' && curl -u {{webinterface_username}}:{{webinterface_password}} -k 'https://localhost:4443/api?action=stopCapture'"
  when: setup_start_stop_capture_cron
