- name: git repo
  git: repo=https://github.com/not-implemented/raspicam-timelapse.git dest="{{repo_path}}"

- name: npm install
  npm: path={{repo_path}}

- name: create capture directory
  file: path="{{ capture_path }}" state=directory

- name: install systemd service
  become: true
  template:
    src: raspicam-timelapse.service
    dest: /etc/systemd/system/raspicam-timelapse.service
    owner: pi
    group: pi
    mode: 0644

- name: read timelapse.json config
  slurp:
    src: "{{ repo_path + '/config/timelapse.json' }}"
  register: timelapse_json_raw
  ignore_errors: true

- name: set timelapse.json config fact
  set_fact: timelapse_json="{{ timelapse_json_raw['content'] | b64decode | from_json }}"
  when: timelapse_json_raw | succeeded

# TODO: don't change if it will be changed by ramdisk role later 
- name: write modified timelapse.json config
  copy: content="{{ timelapse_json | default({}) | combine({ 'capturePath':capture_path }) }}" dest="{{repo_path}}/config/timelapse.json"
  notify: 
  - restart raspicam-timelapse

- name: enable/start systemd service
  become: true
  systemd:
    name: raspicam-timelapse
    enabled: yes
    state: started
    daemon_reload: yes
