---
- hosts: timelapse
  roles:
  - basic-raspi-config
  - nvm
  - basic-facts

- hosts: timelapse
  environment:
    PATH: "{{node_path|default(ansible_env.PATH)}}:{{ ansible_env.PATH }}"
  roles:
  - enable-raspicam
  - wlan
  - { role: umts-backdoor, when: umts_enabled|default(False) }
  - network
  - raspicam-timelapse
  - jdauphant.ssl-certs
  - ssh-tunnel
  - sync
  - capture-ramdisk
  - network-watchdog
