---
- hosts: timelapse
  roles:
  - role: basic-raspi-config
    password: "~encrypted-password~"
    locale: de_DE.UTF-8
    timezone: Europe/Berlin
    sshKey: "~/.ssh/id_rsa.pub"

  - role: nvm
    nvm_version: "v0.32.0"
    node_version: "6"

  - role: basic-facts

- hosts: timelapse
  environment:
    PATH: "{{node_path|default(ansible_env.PATH)}}:{{ ansible_env.PATH }}"
  roles:
  - role: enable-raspicam
  
  - role: wlan
    country: DE

  - role: network
    interfaces:
      eth0:
        iface_inet: manual
      eth1:
        configure_type: allow-hotplug
        iface_inet: dhcp
      wlan0:
        configure_type: allow-hotplug
        iface_inet: manual
        iface:
          wpa-conf: /etc/wpa_supplicant/wpa_supplicant.conf
      wlan1:
        configure_type: allow-hotplug
        iface_inet: manual
        iface:
          wpa-conf: /etc/wpa_supplicant/wpa_supplicant.conf

  - role: raspicam-timelapse
